create database airport_management;
use airport_management;
CREATE TABLE IF NOT EXISTS PASSENGER (
  PASS_NAME varchar(50) NOT NULL,
  PASS_AGE int(2) NOT NULL,
  PASS_PASSPORT_NO int(10) NOT NULL,
  PRIMARY KEY (PASS_PASSPORT_NO));
  CREATE TABLE IF NOT EXISTS AIRLINE (
AIRPLANE_ID VARCHAR(10),
AIRLINE_MANAGER VARCHAR(20),
AIRPLANE_MODEL_NO INT,
AIRLINE_NO_AIRCRAFTS INT,
AIRLINE_NO_OF_EMPLOYEES INT,
PRIMARY KEY (AIRPLANE_ID));
CREATE TABLE ARRIVALS(
AIRPLANE_ID VARCHAR(10),
ARRIVAL_TIME INT(10),
ARRIVAL_LOCATION VARCHAR(20),
ARRIVAL_DELAY INT(10),
PRIMARY KEY (ARRIVAL_LOCATION),
FOREIGN KEY (AIRPLANE_ID) REFERENCES AIRLINE (AIRPLANE_ID));
CREATE TABLE DEPARTURES (
AIRPLANE_ID VARCHAR (10) ,
 DEPART_TIME INT, 
 DEPART_DELAY VARCHAR(10),
 DESTINATION VARCHAR (20), 
 PRIMARY KEY(DESTINATION), 
 FOREIGN KEY(AIRPLANE_ID) REFERENCES AIRLINE (AIRPLANE_ID));
 CREATE TABLE IF NOT EXISTS TICKET (
  AIRPLANE_ID VARCHAR(10) ,
  SEAT_NO int NOT NULL,
  ORIGIN varchar(50) NOT NULL,
  DESTINATION varchar(50) NOT NULL,
  FOREIGN KEY (ORIGIN) REFERENCES ARRIVALS(ARRIVAL_LOCATION),
  FOREIGN KEY (DESTINATION) REFERENCES DEPARTURES(DESTINATION),
  FOREIGN KEY (AIRPLANE_ID) REFERENCES AIRLINE (AIRPLANE_ID));
CREATE TABLE STORES(
STORE_ID INT(15) PRIMARY KEY,
STORE_NAME VARCHAR(15),
STORE_TYPE VARCHAR(10));
CREATE TABLE INTERNATIONAL (
AIRPLANE_ID VARCHAR(10),
INTER_LUGGAGE INT, 
INTER_IMMIGRATION VARCHAR(20),  
DESTINATION VARCHAR(20),
ORIGIN VARCHAR(20),
PASS_PASSPORT_NO INT,
FOREIGN KEY (ORIGIN) REFERENCES ARRIVALS(ARRIVAL_LOCATION),
FOREIGN KEY (DESTINATION) REFERENCES DEPARTURES(DESTINATION),
FOREIGN KEY (AIRPLANE_ID) REFERENCES AIRLINE (AIRPLANE_ID),
FOREIGN KEY (PASS_PASSPORT_NO) REFERENCES PASSENGER (PASS_PASSPORT_NO));
CREATE TABLE AIRCRAFT (
AIRPLANE_ID VARCHAR(10),
AIRLINE_MODEL VARCHAR(10) PRIMARY KEY,
AIRLINE_COMPANY VARCHAR(30), 
CAPACITY INT,
FOREIGN KEY (AIRPLANE_ID) REFERENCES AIRLINE (AIRPLANE_ID));

CREATE TABLE ASSISTANCE ( 
WHEEL_CHAIR VARCHAR(10), 
GOLF_CART VARCHAR(15), 
CARETAKER VARCHAR(15),
PASS_PASSPORT_NO INT,
FOREIGN KEY (PASS_PASSPORT_NO) REFERENCES PASSENGER (PASS_PASSPORT_NO));
CREATE TABLE LUGGAGE ( 
BELT_NO INT, 
LUGGAGE_ID INT, 
PASS_PASSPORT_NO INT,
FOREIGN KEY (PASS_PASSPORT_NO) REFERENCES PASSENGER (PASS_PASSPORT_NO));
CREATE TABLE PARKING(
VEHICLE_NO INT(10) PRIMARY KEY,
PARK_BLOCK VARCHAR(5),
PARK_TIME INT(10)
);
CREATE TABLE DOMESTIC(
DOM_LUGGAGE INT,
DESTINATION VARCHAR(20),
ORIGIN VARCHAR(20),
PASS_PASSPORT_NO INT,
AIRPLANE_ID VARCHAR(10),
FOREIGN KEY (ORIGIN) REFERENCES ARRIVALS(ARRIVAL_LOCATION),
FOREIGN KEY (DESTINATION) REFERENCES DEPARTURES(DESTINATION),
FOREIGN KEY (AIRPLANE_ID) REFERENCES AIRLINE (AIRPLANE_ID),
FOREIGN KEY (PASS_PASSPORT_NO) REFERENCES PASSENGER (PASS_PASSPORT_NO));

CREATE TABLE IF NOT EXISTS EMPLOYEE (
  EMP_ID int(10) ,
  EMP_NAME varchar(50),
  EMP_ADDRESS varchar(50),
  EMP_PHNO int(10),
  EMP_SALARY int(15),
  PRIMARY KEY (EMP_ID)
);

show tables;
select*from passenger;
select*from departures;
select*from airline;
desc airline;
alter table airline modify column airplane_model_no varchar(20);
select*from arrivals;
select*from departures;
select*from ticket;
desc ticket;
alter table ticket modify column seat_no varchar(20);
select*from stores;
select*from international;
select* from aircraft;
desc aircraft;
select*from lounge;
desc lounge;
alter table lounge modify column class_type varchar(30);
select*from assistance;
select*from luggage;
select*from parking;
select*from domestic;
select*from employee;